// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ofsbwaGd6G6VTPK42qp_Wj_1WeANwuc',
    appId: '1:784902004586:web:ce926de5e5e9087576cf13',
    messagingSenderId: '784902004586',
    projectId: 'wordtape-demo',
    authDomain: 'wordtape-demo.firebaseapp.com',
    storageBucket: 'wordtape-demo.appspot.com',
    measurementId: 'G-F89YXK6RWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxYJYb3m0HBbpYmnA30EaIIzaTz91TE0',
    appId: '1:784902004586:android:c30a4f7f6b9929d276cf13',
    messagingSenderId: '784902004586',
    projectId: 'wordtape-demo',
    storageBucket: 'wordtape-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGO9bHM7TlDk1P9yXbd4cgvpAAX2IEFQs',
    appId: '1:784902004586:ios:0b83a7db908bf3a176cf13',
    messagingSenderId: '784902004586',
    projectId: 'wordtape-demo',
    storageBucket: 'wordtape-demo.appspot.com',
    iosBundleId: 'com.hapk.wordtape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGO9bHM7TlDk1P9yXbd4cgvpAAX2IEFQs',
    appId: '1:784902004586:ios:0b83a7db908bf3a176cf13',
    messagingSenderId: '784902004586',
    projectId: 'wordtape-demo',
    storageBucket: 'wordtape-demo.appspot.com',
    iosBundleId: 'com.hapk.wordtape',
  );
}
