// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqKEgP7ZRnJyN3BEhFrXEUbce5OX1g4oc',
    appId: '1:15743304421:web:1fb1d8183e72b7352c4a0c',
    messagingSenderId: '15743304421',
    projectId: 'wordtape-51',
    authDomain: 'wordtape-51.firebaseapp.com',
    storageBucket: 'wordtape-51.appspot.com',
    measurementId: 'G-NW90FRE1L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvzcsFAa8be_4kgpaIj0CQrDDJue7SZw',
    appId: '1:15743304421:android:64b379f955e637bd2c4a0c',
    messagingSenderId: '15743304421',
    projectId: 'wordtape-51',
    storageBucket: 'wordtape-51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWfTzDoZrWg-nzb8iO6amsWw4kJ5fst1U',
    appId: '1:15743304421:ios:61e35562acf98b6d2c4a0c',
    messagingSenderId: '15743304421',
    projectId: 'wordtape-51',
    storageBucket: 'wordtape-51.appspot.com',
    iosBundleId: 'com.hapk.wordtape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWfTzDoZrWg-nzb8iO6amsWw4kJ5fst1U',
    appId: '1:15743304421:ios:61e35562acf98b6d2c4a0c',
    messagingSenderId: '15743304421',
    projectId: 'wordtape-51',
    storageBucket: 'wordtape-51.appspot.com',
    iosBundleId: 'com.hapk.wordtape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqKEgP7ZRnJyN3BEhFrXEUbce5OX1g4oc',
    appId: '1:15743304421:web:ab7dbd8e4d01e17a2c4a0c',
    messagingSenderId: '15743304421',
    projectId: 'wordtape-51',
    authDomain: 'wordtape-51.firebaseapp.com',
    storageBucket: 'wordtape-51.appspot.com',
    measurementId: 'G-5X4L4G62YD',
  );
}
